# Generated by Django 6.0 on 2025-12-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_payment_reference_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(blank=True, null=True, default=None, editable=False, max_length=12, unique=True),
        ),
    ]
