# Generated by Django 6.0 on 2025-12-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_code',
            field=models.CharField(blank=True, default=None, editable=False, max_length=12, null=True, unique=True),
        ),
    ]
